#!/usr/bin/env bash
#
# config: 2 40
# @brief: Save the audit log
#

. $DREPORT_INCLUDE/functions

desc="Audit Log"
file_name="/var/log/audit/audit.log"

if [ -e "$file_name" ]; then
  add_copy_file "$file_name" "$desc"
fi
