#!/usr/bin/env bash
#
# config: 23 50
# @brief: Collect inventory persistent data
#

. $DREPORT_INCLUDE/functions

inventorydir="/var/lib/phosphor-inventory-manager"
if [ -d "$inventorydir" ]; then
    add_copy_file "$inventorydir" "Inventory data"
fi
