#!/bin/bash
#
# config: 2 20
# @brief: Get the pldm flight recorder
#

. $DREPORT_INCLUDE/functions

desc="pldm flight recorder"

# collect data only if pldmd is enabled and has claimed its D-Bus name
# Checking D-Bus name ensures pldmd is fully initialized and has registered signal handlers
if [ -e "/usr/bin/pldmd" ] && busctl status xyz.openbmc_project.PLDM > /dev/null 2>&1; then
    command="rm -rf /tmp/pldm_flight_recorder; killall -s SIGUSR1 pldmd; \
           sleep 5; cat /tmp/pldm_flight_recorder"

    file_name="pldmflightrecorder.log"

    add_cmd_output "$command" "$file_name" "$desc"

    rm -rf /tmp/pldm_flight_recorder
else
    log_warning "skipping pldm flight recorder: pldmd is not enabled or not ready"
fi
